# docker-compose.yaml
version: "3"

services:
  go-todo:
    container_name: go-todo
    image: scottatstchome/go-todo:dev
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "$APP_PORT:$APP_PORT"
      - "$DEBUG_PORT:$DEBUG_PORT"
    networks:
      - go-todo-network
  go-todo-db:
    container_name: go-todo-db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - go-todo-network
volumes:
  postgres-db:     

networks:
  go-todo-network: